var GAME_LEVELS = [
  ["                                                                                  ",
   "  x                                                                               ",
   "  x                                                                               ",
   "  x                                                                               ",
   "  x                                                               xxxxx          x",
   "  x                                                            xx  !!!x  o       x",
   "  x                                                       o   s    !!!x          x",
   "  x                                                                x!xx       s  x",
   "  x   o                              o o                 xxxxxxxxxx!!!xxxxx      x",
   "  x @                                                  xx     xxxxxx!xx!!!!!!xxxxx",
   "  xxx                                            o o  x             !!!!!!!!!xx   ",
   "  x         o                                                       !!!!!!!!!xx   ",
   "  xxxxx             o                  xxx                        o !!!!!!!!!xx   ",
   "  x                     o o       o          x   xx              o  !!!!!!!!!xx   ",
   "  xxxxxxx                                    x!!!x             x    !!!!!!!!!xx   ",
   "  x            xxx  s             xx         x!!!x  xxx   xxx!!!xxxx!!!!!!!!xxx   ",
   "  x              x                           x!!!x!!!!!!!!!!x!!!xxxxx!!!!!!!xxx   ",
   "  xxxxxxxxxx!!!!!xxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxx   ",
   "           x!!!!!x            x!!!!!!x             x!!!!!!!!x                     ",
   "           x!!!!!x            x!!!!!!x              xx!!!!!!x                     ",
   "           x!!!!!x            x!!!!!!x                x!!!!!x                     ",
   "           x!!!!!x            x!!!!!!x                 x!!!x                      ",
   "           x!!!!!x            xxxxxxxx                  xxxx                      ",
   "           xxxxxxx                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "x                                                                                   x                             ",
   "x                                                                                   x                             ",
   "x                                                                                   x                             ",
   "x                                                         v                         x                             ",
   "x                         o                                                         x                             ",
   "x                                                                                   x                             ",
   "x                 o     xxxxxxx                       x                             x                             ",
   "x                    xxx!!     xxxx                   x                             x                             ",
   "x                 xxx!!!!!     v   xxx                x                             x                             ",
   "x               xxxxx!!!!!           x             x  x                      xxx    x                             ",
   "x               xxxxx!!!!!           x    x    x   x  x       o    s  x     x       x                             ",
   "x            xxx=                    x    x    x   x  x               x     x s     x                             ",
   "x    @     xx                        x    x    xxxxxxxx       xxxxxxx x!!!!!x     o x                             ",
   "x          xx o               o                       o       xx      x!!!!!x       x                             ",
   "!!!!xxx!!!!xx                                                x      xxxxxxxxxxxxxxxx                              ",
   "!!!!xxx!!!!xxxxxx   xx  o    xxx                          xxx                                                     ",
   "!!!!!!!!!!!xx!!!!!!!xx                                   x                                                        ",
   "!!!!!!!!!!!xx!!!!!xxxxxxxx         x       xxxx      xx!!!!!!!xx                                                  ",
   "!!!!!!!!xxx!!!!!xx         o                     xxx!!!!!!!xx                                                     ",
   "xx!!!!!!xxxxxxxxxx     s        s      xxxxxxxx!!!!!!xxxxxxxx                                                     ",
   "xxxxxxxxxx!!!!!!x                     x!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!x!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                               o                                              ",
    "                                                                                                              ",
    "                                                  xx          =xx                                             ",
    "                                                             xx  xx                                           ",
    "                                         xx               =xx      xx                                         ",
    "                                                         xx          xx=         xxx                          ",
    "                                                o      xx              xx   o                                 ",
    "                                                     xx                  xx                                   ",
    "                                               xx  xx                      xx                                 ",
    "                                             xx  xx                          xx                               ",
    "                                           xx      xx                          xx                             ",
    "                                         xx          xx                          xx                           ",
    "                                       xx              xx                                                     ",
    "                                     xx                  xx                                                   ",
    "                                                                                                              ",
    "  x                                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
    "  x                           xxxx                                           xxxxv                            ",
    "  x                         xx   x                                    xxxxxxx                              s  ",
    "  x                       xx     xxxxxx                         xxxxxxv                                       ",
    "  x                     xx             xx                   xxxxx                                           xx",
    "  x            o      xx               xxxxxxxxxxxxxxxxxxxxxxx                                       o    xx  ",
    "  x               xxxx                                                                                  xx    ",
    "  x    xxxxxxxxxxx                                                                                 xxxxx      ",
    "  x                                                                       xxxx              o   xxx           ",
    "  x                            xxxxxxxxxxxxxxxxxxxx                       =                                   ",
    "  x                          xxxxxxxxxxxxxxxxxxxxxxxxxxxx      =xxxx                    =xxx                 =",
    "  x                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     s                             ",
    "  x                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          o      xxxxx                       ",
    "  x                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xx                            ",
    "  x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "  x                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "  x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "  x s          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "  x      @   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                                              ",
    "                                                                                                              "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         ",
   "x                                                                                                                                             ",
   "x                                                                                                                                             ",
   "x                                                                                                                                             ",
   "x                                                                                                                                             ",
   "x                                                                                                                                             ",
   "x                                                                                                                                             ",
   "x                                                                  xxxxxxxxxxxxxxxxxxxxxxx                                                    ",
   "x                                                                                                                                             ",
   "x                                  xxxxxxxxxxxxxxxxxxxx                                                                                       ",
   "x                                                                                                                                             ",
   "x            xxxxxxxxxxxxx                                                                                                                    ",
   "xyyyyyyyyyyyyyy	   	yyyyyyyyyyyyy		yyyyyyyyyyyyyyyyy	   yyyyyyyyyyyyyy	  yyyyyyy xxxxxx                                                      ",
   "xyyyy      		       yyyyyyyyyyyyy		yyyyyyyyyyyyyyyyy	   yyyyyyyyyyyyyy	  yyyyyyy                                                           ",
   "xyyyyyyyyy	 	           yyyyy		    yyyyyyyyyyyyyyyyy	   yyyyyyyyyyyyyy	  yyyyyyy                                                           ",
   "xyyyy                   yyyyy		    yyyyy       yyyyy    yyyy      yyyy   yyyyyyy                                                             ",
   "xyyyy                   yyyyy      yyyyy       yyyyy    yyyyyyyyyyyyyy	  yyyyyyy                                    s                        ",
   "xyyyy			            yyyyyyyyyyyyy		yyyyy       yyyyy    yyyy      yyyy	  yyyyyyyyyyyyyyy                                                   ",
   "xyyyy    	          yyyyyyyyyyyyy		yyyyy       yyyyy    yyyy      yyyy	  yyyyyyyyyyyyyyy                       xxxxxxxxxx                    ",
   "x                                                                                                xxxxxxxxxx                                   ",
   "xyyyyyyyyyyyyyy		yyyyyyyyyyyyyy		yyyyyyyyyyyyyyyyy 	   yyyyyyyyyyyyyyy	    yyyyyyyyyyyyyy  xxyyyyyyyyyyyyyy	 yyyyy    yyyyy             ",
   "xyyyy      		    yyyyyyyyyyyyyy		yyyyyyyyyyyyyyyyy	    yyyyyyyyyyyyyyy	    yyyyyyyyyyyyyy    yyyyyy	      	  yyyyy    yyyyy              ",
   "xyyyyyyyyy	 	    yyyyyyyyyyyyyy	 yyyyyyyyyyyyyyyyy          yyyyy		        yyyyyyyyyyyyyyxx  yyyyyy		        yyyyy    yyyyy              ",
   "xyyyy            yyyy      yyyy  yyyyy       yyyyy		        yyyyy	         yyyyxxxxxxyyyy	   yyyyyyyyyyyyyy  yyyyyyyyyyyyyy                 ",
   "xyyyy            yyyyyyyyyyyyyy	 yyyyy       yyyyy		        yyyyxxxxxxxxx  yyyyyyyyyyyyyy	  	        yyyyyy  	     yyyyy                  ",
   "xyyyy		          yyyy      yyyy  yyyyy       yyyyy	xxxxxxx  yyyyy	         yyyy      yyyy	   yyyyyyyyyyyyyy	       yyyyy                    ",
   "xyyyy		          yyyy      yyyy  yyyyy       yyyyy		        yyyyy	         yyyy      yyyy	   yyyyyyyyyyyyyy	       yyyyy                    ",
   "!xx                    xxxxxx     xxxxxx  xxxxxx                                                                                              ",
   "!!x  @   xxxxxxxxxxx   yy yy yyyyy   yy   yy                                                                                                  ",
   "!!xxxxxxx               yy   y   y   yy   yy        yy  yy  yy   yyyyyy  yyyyyy                                                               ",
   "!!!!!!!!x               yy   yyyyy   yyyyyyy        yy  yy  yy     yy    yy  yy                                                         s     ",
   "!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     yyyyyyyyyy   yyyyyy  yy  yy                                                               ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
